#!/usr/bin/env bash

set -euo pipefail

function die {
	>&2 echo "FATAL: ${@:-UNKNOWN ERROR}"
	exit 1
}

type -P kubectl > /dev/null 2>&1 || die "No kubectl found in path."

[ -n "${1:-}" ] || { kubectl config get-contexts; exit 0; }

[ "$(echo "${1}" | wc -l)" == "1" ] || die "Multi-line patterns not supported."

pat="$(echo "${1}" | head -n 1 | sed -e 's/[]\/$*.^[]/\\&/g')"

contexts="$(kubectl config get-contexts --no-headers | sed 's/^*/ /' | awk '$1~/'"${pat}"'/{print $1}' | grep -Ev '^[[:space:]]*$' || true)"

[ -n "${contexts}" ] || die "No results for search string \"${1}\"."

lines="$(echo "${contexts}" | wc -l )"

if [ "${lines}" -eq "1" ]; then
	kubectl config use-context "${contexts}"
else
	echo "Non-unique results:"
	for c in ${contexts}; do
		printf "\t%s\n" "${c}"
	done
	if [ "$(echo "${contexts}" | awk '$1~/^'"${pat}"'$/{print $1}' | wc -l || true)" -eq "1" ]; then
		echo
		echo "\"${1}\" is an exact match. Switching..."
		kubectl config use-context "${1}"
	fi
fi
